Add missing fields in MQTTAsync_disconnectOptions initializer
A missing field initializer is given when initializing a MQTTAsync_disconnectOptions with MQTTAsync_disconnectOptions_initializer.

error: missing initializer for field 'onSuccess5' of 'MQTTAsync_disconnectOptions {aka struct <anonymous>}' [-Werror=missing-field-initializers]
|          MQTTAsync_disconnectOptions opts = MQTTAsync_disconnectOptions_initializer;

Make sure that every disconnect initializer has every field

Signed-off-by: Mohamed Belaouad <mohamed.belaouad@wattsense.com>