Compilation fix: using enum SUCCESS instead of MQTTASYNC_SUCCESS
This commit fixes compilation error:
MQTTAsync.h:1114:143: error: invalid conversion
from ‘int’ to ‘MQTTReasonCodes’ [-fpermissive]

Signed-off-by: Krzysztof Bogucki <kristofbo@gmail.com>